version: '3'
services:
  app:
          #- name: web-app
   build: .
    #image: image_name
   ports:
      - "41579:8080"

  localhost:
          #- name: localhost
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "8125:8125/udp"
      - "8126:8126"
    depends_on:
      - app
